### ISSUE TITLE
Support 'latest' as an alias for the flow version

### ISSUE THREAD

**Issue by aperepel** [bbende/nifi#16]
When promoting flow versions between buckets/registries, it becomes cumbersome to track version numbers. Add support for `latest` as an alias and/or use the latest one if the flow version is omitted. I think the registry api already supports `latest`.

**Comment by bbende** [comment]
I agree, I think we should make the flow version optional on `export-flow-version`, and when it isn't specified we will just export the latest. Will work on this.

The import side will be handled by the other issue where we discussed making the import automatically use the next one up number.
