### ISSUE TITLE
`nifi-reg export-flow-version` command prints unstructured text before json output

### ISSUE THREAD

**Issue by aperepel** [bbende/nifi#17]
The idea behind this command is e.g. to save the output in an external file. However, if I try to redirect the output of the command via `>` operator, it captures additional text, making json invalid.

There is the `--outputFile` arg, but I think it's much more natural for people to expect to save the output via redirect.

The text appears when I have some values in the `~/.nifi-cli.config`, says something like `Session loaded values from ....`. On a clean install and in cases when the user doesn't have any session vars, it will work, but then break randomly depending on the environment.

**Comment by bbende** [comment]
Right now there is a method to create the context & session, and it is called from interactive and standalone mode, so for now I am just going to pass in a boolean to this method to indicate if it is interactive or not, then only print the session messages when in interactive mode.

We can also decide later to only use an in-memory session when in standalone mode, but I will leave that alone for now and we can always change it later.

**Comment by bbende** [comment]
@aperepel looks like issues don't auto-close until they are merged into master, so let me know if you agree with the above fix and then I will manually close this so we can work down the issues.

**Comment by bbende** [comment]
Closing this as I believe it is fixed, can re-open later if it is not.
