### ISSUE TITLE
`nifi-reg import-flow-version` must not require the `--flowVersion` argument

### ISSUE THREAD

**Issue by aperepel** [bbende/nifi#18]
This is quite counterintuitive. We should be either using the flow version from the definition file or default to `latest` on import, i.e. append-only mode. Also, version counts will not necessarily match between buckets/instances, e.g. Dev & Prod, so requiring this arg is not right.

**Comment by bbende** [comment]
I agree, I think it should just become the next one up number. Since we don't have a true import on the registry side, we can just make a call to determine the latest version number of the flow we are importing to, and then make the imported version be the next one-up number. Will work on this.
