### ISSUE TITLE
`nifi import-pg` requires a PG name, but then doesn't use it

### ISSUE THREAD

**Issue by aperepel** [bbende/nifi#19]
The command mandates the PG name argument, but then the imported PG lists whatever was provided in the flow version definition file (which makes sense, we don't rename a PG on import).

However, the PG name from the CLI is then used in the Flow Configuration History, which makes it impossible to track - the UI displays nameA, but the history lists nameB.

**Comment by bbende** [comment]
Good catch, I removed the name option from that command since it will always use the one from registry.
