### ISSUE TITLE
`list-XYZ` commands concise vs verbose output

### ISSUE THREAD

**Issue by aperepel** [bbende/nifi#28]
Related to #20 

I think I have an idea to make things work for automation and great UX. Switch those `list-buckets`, etc commands to a concise output by default. E.g. print only the name and uuid:
```
Bucket A : uuid1
Bucket B : uuid2
```
This will help the interactive shell user quickly copy/paste and navigate.

Then, use the `--verbose` option to print the full json that is used now, with extra metadata, etc. Might roll it into a generic `--json` or similar option instead.

**Comment by bbende** [comment]
Good idea. I'm thinking of adding an `--outputType` with possible values of `simple` and `raw`, or maybe `simple` and `json`. If not specified then default value can be `simple`. This way we can use `--verbose` for other things related to errors or logging
