### ISSUE TITLE
Add a `description` field to the 'registry create-bucket' command

### ISSUE THREAD

**Issue by aperepel** [bbende/nifi#40]
The UI does not yet expose the field, but it's everywhere, depends on https://issues.apache.org/jira/browse/NIFIREG-141

**Comment by bbende** [comment]
This actually already there, the options for create bucket are:
```
 public void doInitialize(final Context context) {
        addOption(CommandOption.BUCKET_NAME.createOption());
        addOption(CommandOption.BUCKET_DESC.createOption());
    }
```
It is an optional argument since it is not required by registry.

**Comment by aperepel** [comment]
I thought the description was missing from the options, I missed it. No worries.
